// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecycleMeApi;

namespace recyclemeapi.Migrations
{
    [DbContext(typeof(RecycleMeApiContext))]
    [Migration("20181130143432_added couple dozen locations")]
    partial class addedcoupledozenlocations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("recyclemeapi.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("CenterName");

                    b.Property<string>("City");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Rating");

                    b.Property<string>("State");

                    b.Property<string>("Zip");

                    b.Property<string>("weekdayHours");

                    b.Property<string>("weekendHours");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new { Id = -1, Address = "2855 109th Ave. N.", CenterName = "Pinellas County Solid Waste", City = "St. Petersburg", Latitude = 27.87395, Longitude = -82.67436, PhoneNumber = "(727) 464-7500", Rating = 3, State = "FL", Zip = "33716", weekdayHours = "Monday-Friday, 9 a.m. to 5:30 p.m.", weekendHours = "Saturday and Sunday, 8 a.m. to 5:30 p.m." },
                        new { Id = -2, Address = "1000 62nd Ave. N.E.", CenterName = "Pinellas County Recycling & Brush Site", City = "St. Petersburg", Latitude = 27.828215, Longitude = -82.62371, PhoneNumber = "", Rating = 3, State = "FL", Zip = "33702", weekdayHours = "Monday-Friday, 9 a.m. to 5:30 p.m.", weekendHours = "Saturday and Sunday, 8 a.m. to 5:30 p.m." },
                        new { Id = -3, Address = "7750 26th Ave. N.", CenterName = "Pinellas County Recycling & Brush Site", City = "St. Petersburg", Latitude = 27.795445, Longitude = -82.704636, PhoneNumber = "", Rating = 3, State = "FL", Zip = "33710", weekdayHours = "Monday-Friday, 9 a.m. to 5:30 p.m.", weekendHours = "Saturday and Sunday, 8 a.m. to 5:30 p.m." },
                        new { Id = -4, Address = "2453 20th Ave. N.", CenterName = "Pinellas County Recycling & Brush Site", City = "St. Petersburg", Latitude = 27.790123, Longitude = -82.666833, PhoneNumber = "", Rating = 3, State = "FL", Zip = "33713", weekdayHours = "Monday-Friday, 9 a.m. to 5:30 p.m.", weekendHours = "Saturday and Sunday, 8 a.m. to 5:30 p.m." },
                        new { Id = -5, Address = "2500 26th Ave. S.", CenterName = "Pinellas County Recycling & Brush Site", City = "St. Petersburg", Latitude = 27.74549, Longitude = -82.66848, PhoneNumber = "", Rating = 3, State = "FL", Zip = "33712", weekdayHours = "Monday-Friday, 9 a.m. to 5:30 p.m.", weekendHours = "Saturday and Sunday, 8 a.m. to 5:30 p.m." },
                        new { Id = -6, Address = "4015 Dr. MLK Jr. St. S.", CenterName = "Pinellas County Recycling & Brush Site", City = "St. Petersburg", Latitude = 27.730649, Longitude = -82.645629, PhoneNumber = "", Rating = 3, State = "FL", Zip = "33712", weekdayHours = "Monday-Friday, 9 a.m. to 5:30 p.m.", weekendHours = "Saturday and Sunday, 8 a.m. to 5:30 p.m." },
                        new { Id = -8, Address = " 1111 18th Ave. S.", CenterName = "Enoch Davis Recreation Center", City = "St. Petersburg", Latitude = 27.752473, Longitude = -82.650372, PhoneNumber = "(727) 893-7134", Rating = 5, State = "FL", Zip = "33705", weekdayHours = "Monday - Tuesday 8:00 am - 8-00 pm  Wednesday 8:00 am - 5:00 pm. Thursday - Friday 8:00 am - 8:00 pm", weekendHours = "" },
                        new { Id = -9, Address = " 1320 5th St. N.", CenterName = "Crescent Lake Drop-Off", City = "St. Petersburg", Latitude = 27.78592, Longitude = -82.640488, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33701", weekdayHours = "", weekendHours = "" },
                        new { Id = -10, Address = "3802 54th Ave. S.", CenterName = "Pinellas Bayway Drop-Off", City = "St. Petersburg", Latitude = 27.71836, Longitude = -82.68205, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33711", weekdayHours = "", weekendHours = "" },
                        new { Id = -11, Address = "4515 38th Ave N", CenterName = "Clearview United Methodist Drop-Off", City = "St. Petersburg", Latitude = 27.806876, Longitude = -82.694447, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33713", weekdayHours = "", weekendHours = "" },
                        new { Id = -12, Address = "4300 Haines Rd.", CenterName = "Grace Lutheran Drop-Off", City = "St. Petersburg", Latitude = 27.810599, Longitude = -82.655398, PhoneNumber = "", Rating = 3, State = "FL", Zip = "33714", weekdayHours = "", weekendHours = "" },
                        new { Id = -13, Address = "300 2nd Ave SE", CenterName = "Municipal Marina Drop-Off", City = "St. Petersburg", Latitude = 27.769472, Longitude = -82.630048, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33701", weekdayHours = "", weekendHours = "" },
                        new { Id = -15, Address = "1023 Gulf Rd", CenterName = "Tarpon Springs Fire Rescue Station 70", City = "Tarpon Springs", Latitude = 28.1449662, Longitude = -82.7722478, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34689", weekdayHours = "", weekendHours = "" },
                        new { Id = -16, Address = "898 S Levis Ave.", CenterName = "Tarpon Springs Yard Waste Facility", City = "Tarpon Springs", Latitude = 28.1381046, Longitude = -82.7503984, PhoneNumber = "(727) 943-0067", Rating = 4, State = "FL", Zip = "34689", weekdayHours = "Monday - Friday, 7am - 4:30pm", weekendHours = "Saturday, 7am - 12pm" },
                        new { Id = -17, Address = "3940 Keystone Rd.", CenterName = "Brooker Creek Education Center", City = "Tarpon Springs", Latitude = 27.9047092, Longitude = -82.6720455, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34688", weekdayHours = "", weekendHours = "" },
                        new { Id = -18, Address = "3940 Keystone Rd.", CenterName = "A.L. Anderson Park, Between Klosterman Rd. and Tarpon Ave ", City = "Tarpon Springs", Latitude = 28.13414, Longitude = -82.738827, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34689", weekdayHours = "", weekendHours = "" },
                        new { Id = -19, Address = "4111 Dunn Dr. ", CenterName = "William E. Dunn Water Reclamation Facility, Off Alt U.S. 19 N", City = "Palm Harbor", Latitude = 28.10988, Longitude = -82.765189, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34683", weekdayHours = "", weekendHours = "" },
                        new { Id = -20, Address = "2200 East Lake Rd.", CenterName = "John Chesnut Sr. Park ", City = "Palm Harbor", Latitude = 28.087942, Longitude = -82.702042, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34685", weekdayHours = "", weekendHours = "" },
                        new { Id = -21, Address = "1825 Curlew Rd. ", CenterName = "Curlew Retention Pond, Between Belcher Rd. and CR 1 ", City = "Palm Harbor", Latitude = 28.049431, Longitude = -82.752827, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34683", weekdayHours = "", weekendHours = "" },
                        new { Id = -22, Address = "1940 Ed Eckert Dr. ", CenterName = "Highlander Park Recycling Site, Across from Highlander Pool ", City = "Dunedin", Latitude = 28.036594, Longitude = -82.777803, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34698", weekdayHours = "", weekendHours = "" },
                        new { Id = -23, Address = "817 Lake Haven Rd. ", CenterName = "Lake Haven Recycling Center", City = "Dunedin", Latitude = 28.017087, Longitude = -82.770546, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34698", weekdayHours = "", weekendHours = "" },
                        new { Id = -24, Address = "3095 McMullen Booth Rd", CenterName = "Safety Harbor Fire Station 53", City = "Clearwater", Latitude = 28.033941, Longitude = -82.708135, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33761", weekdayHours = "", weekendHours = "" },
                        new { Id = -25, Address = "1200 Railroad Ave", CenterName = "Safety Harbor Public Works", City = "Safety Harbor", Latitude = 27.999967, Longitude = -82.69599, PhoneNumber = "", Rating = 4, State = "FL", Zip = "34695", weekdayHours = "", weekendHours = "" },
                        new { Id = -26, Address = "29582 U.S. 19 N", CenterName = "North County Service Center,  West side, south of Curlew Rd.", City = "Clearwater", Latitude = 28.034406, Longitude = -82.732479, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33761", weekdayHours = "", weekendHours = "" },
                        new { Id = -27, Address = "1701 N Hercules Ave.", CenterName = "Clearwater Solid Waste Facility", City = "Clearwater", Latitude = 27.982803, Longitude = -82.752747, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33765", weekdayHours = "", weekendHours = "" },
                        new { Id = -28, Address = "23106 U.S. 19 N", CenterName = "Walmart, SE corner of parking lot", City = "Clearwater", Latitude = 27.983581, Longitude = -82.731369, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33765", weekdayHours = "", weekendHours = "" },
                        new { Id = -29, Address = "1060 Gulf Blvd", CenterName = "Sand Key Park", City = "Clearwater", Latitude = 27.96442, Longitude = -82.82241, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33767", weekdayHours = "", weekendHours = "" },
                        new { Id = -30, Address = "1075 Ponce de Leon Blvd.", CenterName = "John J. Osborne Public Works Building", City = "Belleair", Latitude = 27.933655, Longitude = -82.800926, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33756", weekdayHours = "", weekendHours = "" },
                        new { Id = -31, Address = "6635 Dr. MLK Jr. St. N", CenterName = "Fossil Park", City = "St. Petersburg", Latitude = 27.82923, Longitude = -82.64527, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33702", weekdayHours = "", weekendHours = "" },
                        new { Id = -32, Address = "2331 60th Ave. N", CenterName = "Northwest Park", City = "St. Petersburg", Latitude = 27.79295, Longitude = -82.715668, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33710", weekdayHours = "", weekendHours = "" },
                        new { Id = -33, Address = "3745 9th Ave. N", CenterName = "St. Petersburg Public Library", City = "St. Petersburg", Latitude = 27.78169, Longitude = -82.684268, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33713", weekdayHours = "", weekendHours = "" },
                        new { Id = -34, Address = "7000 4th St. S", CenterName = "Bay Vista Park", City = "St. Petersburg", Latitude = 27.704539, Longitude = -82.641212, PhoneNumber = "", Rating = 4, State = "FL", Zip = "33705", weekdayHours = "", weekendHours = "" }
                    );
                });

            modelBuilder.Entity("recyclemeapi.Models.LocationMaterials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LocationId");

                    b.Property<int>("MaterialsId");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MaterialsId");

                    b.ToTable("LocationMaterials");

                    b.HasData(
                        new { Id = -1, LocationId = -1, MaterialsId = -1 },
                        new { Id = -29, LocationId = -1, MaterialsId = -2 },
                        new { Id = -30, LocationId = -1, MaterialsId = -3 },
                        new { Id = -31, LocationId = -1, MaterialsId = -4 },
                        new { Id = -32, LocationId = -1, MaterialsId = -5 },
                        new { Id = -33, LocationId = -1, MaterialsId = -6 },
                        new { Id = -34, LocationId = -1, MaterialsId = -7 },
                        new { Id = -35, LocationId = -1, MaterialsId = -8 },
                        new { Id = -36, LocationId = -1, MaterialsId = -9 },
                        new { Id = -2, LocationId = -2, MaterialsId = -2 },
                        new { Id = -3, LocationId = -3, MaterialsId = -3 },
                        new { Id = -4, LocationId = -4, MaterialsId = -4 },
                        new { Id = -5, LocationId = -5, MaterialsId = -5 },
                        new { Id = -6, LocationId = -6, MaterialsId = -6 },
                        new { Id = -8, LocationId = -8, MaterialsId = -8 },
                        new { Id = -9, LocationId = -9, MaterialsId = -9 },
                        new { Id = -10, LocationId = -10, MaterialsId = -1 },
                        new { Id = -11, LocationId = -11, MaterialsId = -2 },
                        new { Id = -12, LocationId = -12, MaterialsId = -3 },
                        new { Id = -13, LocationId = -13, MaterialsId = -4 },
                        new { Id = -14, LocationId = -14, MaterialsId = -5 },
                        new { Id = -15, LocationId = -14, MaterialsId = -6 },
                        new { Id = -16, LocationId = -15, MaterialsId = -1 },
                        new { Id = -17, LocationId = -15, MaterialsId = -8 },
                        new { Id = -18, LocationId = -16, MaterialsId = -1 },
                        new { Id = -19, LocationId = -16, MaterialsId = -3 },
                        new { Id = -20, LocationId = -16, MaterialsId = -5 },
                        new { Id = -21, LocationId = -16, MaterialsId = -8 },
                        new { Id = -22, LocationId = -16, MaterialsId = -9 },
                        new { Id = -23, LocationId = -16, MaterialsId = -7 },
                        new { Id = -24, LocationId = -15, MaterialsId = -3 },
                        new { Id = -25, LocationId = -15, MaterialsId = -5 },
                        new { Id = -26, LocationId = -15, MaterialsId = -9 },
                        new { Id = -27, LocationId = -17, MaterialsId = -1 },
                        new { Id = -28, LocationId = -17, MaterialsId = -3 }
                    );
                });

            modelBuilder.Entity("recyclemeapi.Models.Materials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MaterialType");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new { Id = -1, MaterialType = "Plastic" },
                        new { Id = -2, MaterialType = "Metal" },
                        new { Id = -3, MaterialType = "Paper" },
                        new { Id = -4, MaterialType = "Electronics" },
                        new { Id = -5, MaterialType = "Glass" },
                        new { Id = -6, MaterialType = "Chemicals" },
                        new { Id = -7, MaterialType = "Yard Waste" },
                        new { Id = -8, MaterialType = "Cardboard" },
                        new { Id = -9, MaterialType = "Aluminum Cans" }
                    );
                });

            modelBuilder.Entity("recyclemeapi.Models.LocationMaterials", b =>
                {
                    b.HasOne("recyclemeapi.Models.Location", "Location")
                        .WithMany("LocationMaterials")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("recyclemeapi.Models.Materials", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
