// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using recyclemeapi;

namespace recyclemeapi.Migrations
{
  [DbContext(typeof(RecycleMeApiContext))]
  [Migration("20181113154804_AddedLocationandRecyclingCenters")]
  partial class AddedLocationandRecyclingCenters
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
          .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      modelBuilder.Entity("recyclemeapi.Models.Location", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd();

            b.Property<string>("Address");

            b.Property<string>("City");

            b.Property<string>("ImageUrl");

            b.Property<string>("PhoneNumber");

            b.Property<int>("Rating");

            b.Property<int>("Recycles");

            b.Property<int>("RecyclingCenterId");

            b.Property<string>("State");

            b.Property<string>("Zip");

            b.HasKey("Id");

            b.HasIndex("RecyclingCenterId");

            b.ToTable("Locations");
          });

      modelBuilder.Entity("recyclemeapi.Models.RecyclingCenter", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd();

            b.Property<string>("Brand");

            b.HasKey("Id");

            b.ToTable("RecyclingCenter");
          });

      modelBuilder.Entity("recyclemeapi.Models.Location", b =>
          {
            b.HasOne("recyclemeapi.Models.RecyclingCenter", "RecyclingCenter")
                      .WithMany("Locations")
                      .HasForeignKey("RecyclingCenterId")
                      .OnDelete(DeleteBehavior.Cascade);
          });
#pragma warning restore 612, 618
    }
  }
}
